services:
  matey-exporter:
    image: therealscienta/matey_exporter:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config.yml:/app/config.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3